POINTING_DEVICE = trackpoint
POINTING_DEVICE_POSITION = left
OLED = yes

VIA_ENABLE = no
OLED_ENABLE = yes
MOUSEKEY_ENABLE = yes
EXTRAKEY_ENABLE = yes
CAPS_WORD_ENABLE = yes
RGB_MATRIX_ENABLE = yes
RGBLIGHT_ENABLE = no
